name: release
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: dependencies
        run: ./gradlew --no-daemon dependencies
      - name: Build and Release with Gradle
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: ./gradlew --no-daemon build publish -x test